server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/help?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root


  mybatis:
     mapper-locations: classpath:com.example.help.mapper/*.xml
     type-aliases-package: com.example.help.domain
     mapper:
        mappers: com.demo.help.TkMapper
        identity: MYSQL

  logging:
     config: classpath:log4j2.yml


  redis:
      # 使用的数据库，默认为0
      database: 1
      # host主机，默认为localhost
      host: 127.0.0.1
      # 端口号,默认为6379
      port: 6379
      # 密码，默认为空
      password:

  rabbitmq:
      port: 5672

  http:
    encoding:
      charset: utf-8
      enabled: true





